### ISSUE TITLE
Make targets easily accessible for scaling

### ISSUE THREAD

**Issue by timkucera** [BorgwardtLab/proteinshake#125]
also for fitting label binarizers etc. I think this would be best put into the task classes

**Comment by cgoliver** [comment]
@timkucera do you have more detail on what you mean for this?

**Comment by timkucera** [comment]
That was from a discussion with Dexiong when he wanted to fit a scaler on the data. For now what you have to do is:

```
ds = AlphaFoldDataset(...)
proteins, size = ds.proteins()
y = np.array([task.target(protein_dict) for protein_dict in proteins])[task.train_ind]
```

to get all the target values. Which is ok but rather awkward. It would be good if the targets were easily accessible from the task (i.e. I don't have to call `task.target` myself but maybe something like a `task.y_train` property which executes above code). Same goes for fitting binarizers in classification tasks.

**Comment by timkucera** [comment]
done
