### ISSUE TITLE
Could you provide the script for building structure-similarity splits?

### ISSUE THREAD

**Issue by LTEnjoy** [BorgwardtLab/proteinshake#267]
Hi, thank you for your wonderful work!

I'm very interested in your proposed novel way to construct datasets based on structure similarity using foldseek. I wonder that if you could share the script to build the **structure-similarity split** as described in your paper?

Thank you very much and looking forward to your reply!

**Comment by cgoliver** [comment]
Thanks for your interest in ProteinShake!

All of the pre-processing scripts can be found in our release script repository [here](https://github.com/BorgwardtLab/proteinshake_release/blob/main/structure_split.py)

Please let us know if you have any other questions!
