### ISSUE TITLE
Miss match of sequence length, residue_number and residue_type

### ISSUE THREAD

**Issue by zpengmei** [BorgwardtLab/proteinshake#274]
Hi team,

Thanks for this helpful repository! I am trying to load some protein datasets here, and there seems be to some discrepancy between the atom-level residue type and numbers that assign atoms to residues. Here is my test function:

```python
from proteinshake.datasets import EnzymeCommissionDataset
dataset = EnzymeCommissionDataset()
proteins = dataset.proteins(resolution='atom')
protein_dict = next(proteins)

print(protein_dict['protein']['ID'])
print('seq length:', len(protein_dict['protein']['sequence']))
print(count_segments(protein_dict['atom']['residue_number']).shape)
print(count_segments(protein_dict['atom']['residue_type']).shape)

print(
    count_segments(protein_dict['atom']['residue_number']),
    '\n',
    count_segments(protein_dict['atom']['residue_type'])
)

print(protein_dict['atom']['residue_number'][-20:])
print(protein_dict['atom']['residue_type'][-20:])
``` 
Here is the output: 
```
1KG6
seq length: 225
(224,)
(210,)
...
...
[222, 222, 222, 222, 223, 223, 223, 223, 223, 223, 223, 223, 223, 224, 224, 224, 224, 224, 224, 224]
['K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'P', 'P', 'P', 'P', 'P', 'P', 'P']
``` 

When looking at the last 20 entries of residue_number and residue type, it seems not matching, like 222 and 223 all refer to K, is this something specific to this dataset? 

Thanks!
Zihan

**Comment by cgoliver** [comment]
Thank you @zpengmei ! We are looking into it. 

Carlos

**Comment by cgoliver** [comment]
Hello @zpengmei could you share the code for `count_segments` so I can fully reproduce your code? Thanks!

**Comment by zpengmei** [comment]
Hi Carlos, 

Thank you so much for your time! Sry for the late reply, I think I missed it there there two 'K'. 

Best,
Zihan
