### ISSUE TITLE
check dgl

### ISSUE THREAD

**Issue by timkucera** [BorgwardtLab/proteinshake#36]
- check all attributes are included

**Comment by cgoliver** [comment]
@timkucera the `.dgl()` method returns a list of two items with the second item being an empty dict. Do you know what is the intended function? The first item in the list is the list of DGL graphs which looks good.

```python
>>> d = ECDataset(root="./data").to_graph(k=2).dgl() 
>>> len(d)
2
>>> d[1]
{}
>>> 
```

**Comment by timkucera** [comment]
mh looks like a bug, that should return the second protein graph...

**Comment by cgoliver** [comment]
ok ill keep digging

**Comment by timkucera** [comment]
closing in favor of #72
