### ISSUE TITLE
Bug with "residue_index" attribute

### ISSUE THREAD

**Issue by claying** [BorgwardtLab/proteinshake#63]
There are two bugs with the "residue_index" attributes:
- it should be a long tensor, but it's a float tensor
- PyG automatically increment attributes ending with an "index" by the number of nodes in the previous graphs in a batch. However, residue_index indicates the absolute positions of residues in each graph and should be affected by other graphs in the batch. A simple remedy could be rename it with "residue_idx" or "residue_position".

**Comment by timkucera** [comment]
it's now "residue_number"
